site_name: APS Docs
theme:
  name: material
plugins:
  - search
  - literate-nav
  - section-index
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google     # albo: numpy
            show_source: true
nav:
  - Wprowadzenie: index.md
  - API:
      - avena_commons: api/avena_commons.md
      - io_event_listener: api/io/io_event_listener.md
      - orchestrator: api/orchestrator/orchestrator.md
