[build-system]
requires = ["setuptools>=75.1.0", "setuptools_scm", "pytest>=7.0", "pytest-cov"]
build-backend = "setuptools.build_meta"

[project]
name = "avena_commons"
version = "2.1.1"
description = "A small utility library for working with Avena Robotics"
authors = [
    { name = "Avena Robotics", email = "lukasz.lecki@pomagier.info" },
]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent"
]
dependencies = [
    "psutil",
    "numpy==1.26.4",
    "scipy",
    'posix-ipc; platform_system=="Linux"',
    "opencv-python",
    "pydantic",
    "requests",
    "uvicorn",
    "httpx",
    "fastapi",
    "flask",
    "dotenv",
    "pysoem",
    "pymodbus==3.9.2",
    "ruff",
    "aiohttp"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov",
    "pytest-asyncio",
    "ruff",
    "black",
    "mypy",
    "build",
    "tox"
]
test = [
    "pytest>=7.0", 
    "pytest-cov",
    "pytest-asyncio"
]

[project.scripts]
run_system_dashboard = "avena_commons.system_dashboard.app:run_app"

[project.urls]
Homepage = "https://github.com/avena-robotics/avena_commons"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "--continue-on-collection-errors --tb=short"
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]



[tool.ruff]
line-length = 88
select = ["E", "W", "F", "I"]
ignore = ["E501"]

[tool.black]
line-length = 88

[tool.setuptools.package-data]
avena_commons = ["vision/data/*.png"]