[build-system]
requires = ["setuptools>=75.1.0"]
build-backend = "setuptools.build_meta"
[project]
name = "avena_commons"
version = "1.0.0"
authors = [
  { name="Avena Robotics", email="author@example.com" },
]
description = "A small utility library for working with Avena Robotics"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: APACHE-2.0",
    "Operating System :: Ubuntu",
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"