FAIRINO_ERROR_CODES = {
    0: {"name": "trouble-free", "sub_codes": {0: "trouble-free"}},
    1: {
        "name": "command point error",
        "sub_codes": {
            1: "Joint command point error, resettable",
            2: "Line mark error (including tool mismatch), reset",
            3: "Arc middle point error (including tool mismatch), reset",
            4: "Arc eye mark error (including tool mismatch), reset",
            5: "Arc command point spacing is too small, can be reset",
            6: "Round/spiral line middle point 1 error (including tool mismatch), reset",
            7: "Round/spiral line middle point 2 error (including tool mismatch), reset",
            8: "Round/spiral line middle point 3 error (including tool mismatch), reset",
            9: "Round/spiral command point spacing is too small, can be reset",
            10: "TPD command point error, resettable",
            11: "TPD command tool does not match current tool, resettable",
            12: "TPD The deviation between the current instruction and the starting point of the next instruction is too large and can be reset",
            13: "Internal and external tool switching error, resettable",
            14: "New helix starts at wrong point, resettable",
            15: "New Spline Command Point Error, Resetable",
            17: "PTP joint command overrun, resettable",
            18: "TPD joint command overrun, resettable",
            19: "LIN/ARC issued joint command overrun, reset",
            20: "Command overspeed in Cartesian space, non-resettable",
            21: "The torque command in the joint space exceeds the limit and can be reset",
            22: "JOG joint command overrun, resettable",
            23: "Command speed in joint space of axis 1 exceeds limit and can be reset",
            24: "Command speed in joint space of axis 2 exceeds limit and can be reset",
            25: "Axis 3 command speed in joint space exceeds limit, resettable",
            26: "Command speed in joint space of axis 4 exceeds limit and can be reset",
            27: "Command speed in joint space of axis 5 exceeds limit and can be reset",
            28: "Axis 6 command speed in joint space exceeds limit and can be reset",
            29: "Joint feedback speed exceeds limit and cannot be reset",
            30: "The deviation between joint command and feedback is too large. It cannot be reset. Restart is required",
            31: "DMP punctuation error (including tool mismatch), resettable",
            33: "Next command joint configuration changes (next command has singular pose, please use PTP command or change next command point), reset",
            34: "Current command joint configuration changes (next command has singular pose, please use PTP command or change next command point), reset",
            49: "Command error, only LIN and ARC commands allowed between ARCSTART and ARCEND, resettable",
            50: "Command error, only LIN and ARC commands allowed between WEAVESTART and WEAVEEND, resettable",
            51: "Swing welding parameter error, resettable",
            52: "Swing welding command point spacing is too small, reset",
            65: "Laser sensor command deviation is too large, reset",
            66: "Laser sensor command interrupted, weld tracking ended early, resettable",
            81: "External shaft command speed overrun, resettable",
            82: "External axis command and feedback deviation is too large, can not be reset, need to return to zero or restart",
            83: "Extended peripheral (external axis/IO) abnormal communication, non-resettable",
            97: "Conveyor tracking-excessive change in attitude from start point to reference point, resettable",
            113: "Constant force control-X direction exceeds maximum adjustment distance, resettable",
            114: "Constant force control-Y direction exceeds maximum adjustment distance, resettable",
            115: "Constant force control-Z direction exceeds maximum adjustment distance, resettable",
            116: "Constant force control-RX direction exceeds maximum adjustment angle, resettable",
            117: "Constant force control-RY direction exceeds maximum adjustment angle, resettable",
            118: "Constant force control-RZ direction exceeds maximum adjustment angle, resettable",
            119: "External sensor data error, resettable",
            120: "Spiral exploration movement failed, reset",
            121: "Rotary insertion movement failed, resettable",
            122: "Linear insertion motion fails, resettable",
            123: "Surface positioning movement failed, resettable",
            129: "Reset if maximum torque recording points are exceeded",
        },
    },
    2: {
        "name": "drive failure",
        "sub_codes": {
            1: "1 Shaft drive fault, non-resettable",
            2: "2 Shaft drive fault, non-resettable",
            3: "3 Shaft drive fault, non-resettable",
            4: "4 Shaft drive fault, non-resettable",
            5: "5 Shaft drive fault, non-resettable",
            6: "6 Shaft drive fault, non-resettable",
        },
    },
    3: {
        "name": "soft limit exceeded fault",
        "sub_codes": {
            1: "1 Shaft exceeds soft limit fault, resettable",
            2: "2 Shaft exceeds soft limit fault, resettable",
            3: "3 Shaft exceeds soft limit fault, resettable",
            4: "4 Shaft exceeds soft limit fault, resettable",
            5: "5 Shaft exceeds soft limit fault, resettable",
            6: "6 Shaft exceeds soft limit fault, resettable",
        },
    },
    4: {
        "name": "collision fault",
        "sub_codes": {
            1: "1 Shaft collision fault, resettable",
            2: "2 Shaft collision fault, resettable",
            3: "3 Shaft collision fault, resettable",
            4: "4 Shaft collision fault, resettable",
            5: "5 Shaft collision fault, resettable",
            6: "6 Shaft collision fault, resettable",
            7: "End collision fault, resettable",
        },
    },
    5: {"name": "Wrong number of active slaves", "sub_codes": {1: "The number of active slave stations is incorrect, and cannot be reset"}},
    6: {
        "name": "slave station error",
        "sub_codes": {
            1: "Lost from station, not reset",
            2: "The slave station status is inconsistent with the setting value, and cannot be reset",
            3: "The slave station is not configured and cannot be reset",
            4: "Slave station configuration error, unresettable",
            5: "Slave initialization error, unresettable",
            6: "Slave mailbox communication initialization error, unresettable",
        },
    },
    7: {
        "name": "IO Error",
        "sub_codes": {
            1: "Channel error, resettable",
            2: "Value error, resettable",
            3: "WaitDI wait timeout, resettable",
            4: "WaitAI wait timeout, resettable",
            5: "WaitAxleDI wait timeout, resettable",
            6: "WaitAxleAI wait timeout, resettable",
            7: "Channel configured function error, resettable",
            8: "Arc ignition timeout, resettable",
            9: "Arc closing timeout, resettable",
            10: "Position finding timeout, resettable",
            11: "Belt IO detection timeout, resettable",
            12: "WaitAuxDI wait timeout, resettable",
            13: "WaitAuxAI wait timeout, resettable",
        },
    },
    8: {"name": "Gripper error", "sub_codes": {1: "Gripper movement timeout error, resettable"}},
    9: {
        "name": "file error",
        "sub_codes": {
            1: "zbt profile version error, initialization error-non-resettable",
            2: "zbt configuration file loading failed, initialization error-not resettable",
            3: "user profile version error, initialization error-non-resettable",
            4: "user profile loading failed, initialization error-not resettable",
            5: "exaxis configuration file version error, initialization error-non-resettable",
            6: "exaxis configuration file loading failed, initialization error-non-resettable",
            7: "Robot models are inconsistent and need to be reset-non-resettable",
            8: "dhpara Configuration file version error, initialization error-non-resettable",
            9: "dhpara Configuration file load failed, initialization error-non-resettable",
            10: "Robot model not set-not resettable",
        },
    },
    10: {"name": "singular pose", "sub_codes": {1: "singular pose"}},
    11: {
        "name": "Drive communication error",
        "sub_codes": {
            1: "1 Shaft drive communication error, non-resettable",
            2: "2 Shaft drive communication error, non-resettable",
            3: "3 Shaft drive communication error, non-resettable",
            4: "4 Shaft drive communication error, non-resettable",
            5: "5 Shaft drive communication error, non-resettable",
            6: "6 Shaft drive communication error, non-resettable",
        },
    },
    12: {"name": "other errors", "sub_codes": {}},
}
